name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  keychain-name:
    description: 'The name of the keychain to create'
    required: true
    default: 'github-actions'

  keychain-password:
    description: 'The password for the keychain'
    required: true

  keychain-timeout:
    description: 'The timeout for the keychain'
    required: true
    default: '3600'

  signing-certificates:
    description: 'The base64 encoded signing certificates'
    required: true

  signing-certificate-passphrase:
    description: 'The passphrase for the signing certificates'
    required: true

# Define your outputs here.
outputs:
  keychain-name:
    description: 'The name of the keychain that was created'

runs:
  using: node20
  main: dist/index.js
